version: '3.8'
services:
  Carbonate:
    image: postgres:14-alpine
    restart: always
    container_name: Carbonate-db
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db: