Services:
  - name: Notion
    machine_name: notion
    img: "https://cdn.icon-icons.com/icons2/2389/PNG/512/notion_logo_icon_145025.png"
    desc: A powerful and collaborative note-taking application.
  - name: Mailchimp
    machine_name: mailchimp
    img: "https://cdn.icon-icons.com/icons2/3398/PNG/512/mailchimp_logo_icon_214765.png"
    desc: An email marketing and automation platform.
  - name: Facebook
    machine_name: facebook
    img: "https://cdn.icon-icons.com/icons2/2429/PNG/512/facebook_logo_icon_147291.png"
    desc: A popular social network to connect with friends and share content.
  - name: Stripe
    machine_name: stripe
    img: "https://cdn.icon-icons.com/icons2/390/PNG/512/stripe_logo_icon_231019.png"
    desc: A leading payment processing platform for businesses, offering secure online payments, subscription management, and advanced features for simplified payment operations.